apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shortlink

resources:
  - shortlink-deployment.yaml
  - shortlink-service.yaml

patches:
  - path: sync-wave-patch.yaml
    target:
      kind: Deployment
      name: shortlink