apiVersion: v1
kind: Service
metadata:
  name: shortlink
  labels:
    app: shortlink
spec:
  type: ClusterIP
  selector:
    app: shortlink
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081