apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kafka.yaml
  - kafka-create-topic-job.yaml
  # Web UI for Kafka monitoring (topics, brokers, consumers, messages)
  - kafka-ui.yaml

