apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shortlink

resources:
  - admin-deployment.yaml
  - admin-service.yaml

patches:
  - path: sync-wave-patch.yaml
    target:
      kind: Deployment
      name: admin