apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shortlink-dev
  namespace: argocd
spec:
  project: shortlink
  source:
    repoURL: https://Rururita1027/Shortlink-GitOps.git
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: shortlink
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

