apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shortlink

resources:
  - ../../../base/clickhouse/

# Dev environment: smaller resources, single replica
patches:
  - path: clickhouse-dev-patch.yaml
    target:
      kind: StatefulSet
      name: clickhouse