apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres/
  - redis/
  - kafka/
  - clickhouse/
  # ArgoCD PostSync jobs; sync from ArgoCD server triggers job execution
  - flyway/