apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres/
  - redis/
  - kafka/
  - clickhouse/
  # ArgoCD is ready, and the ArgoCD app listens to this path, 
  # uncommom jobs, sync from ArgoCD server will automatically trigger the two jobs executions
  - flyway-admin-job.yaml
  - flyway-shortlink-job.yaml

