apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shortlink

resources:
  - ../../../base/clickhouse/

# Prod environment: larger resources, optimized for production
patchesStrategicMerge:
  - clickhouse-prod-patch.yaml
